#!/bin/sh

APPDIR=$(readlink -f "$0")
APPDIR=$(dirname "$APPDIR")
java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/CylinDrawRunMode.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-aarch64.jar:$APPDIR/lib/gluegen-rt-natives-linux-aarch64.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/batik-awt-util-1.8.jar:$APPDIR/lib/batik-dom-1.8.jar:$APPDIR/lib/batik-ext-1.8.jar:$APPDIR/lib/batik-svggen-1.8.jar:$APPDIR/lib/batik-util-1.8.jar:$APPDIR/lib/batik-xml-1.8.jar:$APPDIR/lib/svg.jar:$APPDIR/lib/batikfont.jar:$APPDIR/lib/geomerative.jar:$APPDIR/lib/dxf.jar" CylinDrawRunMode "$@"
